// demos/tools-app-angular/src/app/car-tool/components/car-table/car-table.component.ts
import { Component, Input,  Output, EventEmitter } from '@angular/core';
import { NgFor } from '@angular/common';

import { Car } from '../../models/cars';

@Component({
  selector: 'app-car-table',
  standalone: true,
  imports: [NgFor],
  templateUrl: './car-table.component.html',
  styleUrl: './car-table.component.css'
})
export class CarTableComponent {

  @Input()
  cars: Car[] = [];

  @Output()
  deleteCar = new EventEmitter<number>();

  doDeleteCar(carID: number) {
    this.deleteCar.emit(carID);
  }

}
<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Make</th>
      <th>Model</th>
      <th>Year</th>
      <th>Color</th>
      <th>Price</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <tr *ngFor="let car of cars">
      <td>{{car.id}}</td>
      <td>{{car.make}}</td>
      <td>{{car.model}}</td>
      <td>{{car.year}}</td>
      <td>{{car.color}}</td>
      <td>{{car.price}}</td>
      <td>
        <button type="button" (click)="doDeleteCar(car.id)">Delete</button>
      </td>
    </tr>
  </tbody>
  </table>

// demos/tools-app-react/src/components/CarTable.jsx
import { useCallback } from 'react';
import { CarViewRow } from './CarViewRow';

export function CarTable({ cars, onDeleteCar: deleteCar }) {

  // const deleteCar = useCallback((carId) => {
  //   onDeleteCar(carId);
  // }, [onDeleteCar]);

  return (
    <table>
      <thead>
        <tr>
          <th>Id</th>
          <th>Make</th>
          <th>Model</th>
          <th>Year</th>
          <th>Color</th>
          <th>Price</th>
          <th>Actions</th>
        </tr>
      </thead>          
      <tbody>
      {cars.map(car => (
        <CarViewRow key={car.id} car={car}
          onDeleteCar={deleteCar} />
      ))}
      </tbody>
    </table>
  );

}
